#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Orchestra\Testbench\Foundation\Application(
    basePath: __DIR__.'/vendor/orchestra/testbench-core/laravel',
)->create();

$app->register(\Vistik\LaravelCodeAnalytics\LaravelCodeAnalyticsServiceProvider::class);

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
